# Generated by Django 5.1.4 on 2025-01-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, unique=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(default='usuario@uv.mx', max_length=70, unique=True)),
                ('private_key_encrypted', models.BinaryField(default=b'')),
                ('public_key', models.TextField(null=True)),
                ('iv', models.CharField(max_length=32, null=True)),
                ('salt', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
