# Generated by Django 5.1.4 on 2025-01-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nimbus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
